project_name: agentfield

before:
  hooks:
    - npm --prefix control-plane/web/client ci
    - npm --prefix control-plane/web/client run build

builds:
  - id: agentfield
    dir: control-plane
    main: ./cmd/af
    binary: agentfield
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}
    tags:
      - embedded

archives:
  - id: agentfield
    builds:
      - agentfield
    name_template: "agentfield-{{ .Os }}-{{ .Arch }}"
    format: binary
    files:
      - none

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

release:
  github:
    owner: Agent-Field
    name: agentfield
  draft: false
  prerelease: auto
  name_template: "AgentField v{{.Version}}"
  header: |
    ## AgentField v{{.Version}}

    ### Installation

    ```bash
    curl -fsSL https://agentfield.ai/install.sh | bash
    ```

    Or with version pinning:

    ```bash
    VERSION={{.Version}} curl -fsSL https://agentfield.ai/install.sh | bash
    ```

    ### Manual Download

    Download the binary for your platform below, make it executable, and move it to your PATH.

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
