# Test for issue #559: Execution full content is output to stdout
# Auto-generated by PR Harness

import pytest


def test_issue_559():
    """Regression test for issue #559."""
    # TODO: implement proper test reproduction
    # Issue: Execution full content is output to stdout
    pass

