# Test for issue #436: [Go SDK] AI client flattens structured error responses into fmt.Errorf
# Auto-generated by PR Harness

import pytest


def test_issue_436():
    """Regression test for issue #436."""
    # TODO: implement proper test reproduction
    # Issue: [Go SDK] AI client flattens structured error responses into fmt.Errorf
    pass

